### ISSUE TITLE
ranking score

### ISSUE THREAD

**Issue by noahzn** [jomariya23156/SuperGlue-for-Visual-Place-Recognition#2]
Hi, thanks for your work.

I want to ask why the ranking score uses `np.multiply(matches,match_confidence)`? Here `matches` should be the indexes of the matches, is it meaningful to multiply it with the matching confidence?

**Comment by jomariya23156** [comment]
Honestly, I've forgotten the intuition behind this calculation. It's been three years and this was my internship project. So, I haven't worked with it since then. If `matches` does indeed represent indices, it doesn't make sense to me either.

As I remember, this started as a simple ranking metric, but it performed surprisingly well in testing, so we never revisited it. A quick look at the SuperGlue code comments suggests that the index can be **-1** for unmatched locations. One possibility is that the element-wise multiplication **acts as a penalty** for unmatched locations, balancing the score from positive matches (though the scale is different since the index is the multiplier). Ultimately, this score is normalized by the full score (obtained from matching the query image with itself, which should be very high). This makes the score relative rather than absolute, and you could potentially use a threshold to determine correct matches. SuperGlue itself is accurate, so if there aren't many high-confidence false positives, this approach might work well enough.

Feel free to open a PR if you have a better metric. I don't have time to investigate this right now. If you could provide example values for those two variables, it might help me remember more. :)

**Comment by noahzn** [comment]
Hi, thank you very much for your prompt reply. Currently I only accumulate the matching confidences and it also works. I need to do more tests to see which one is better. I am closing this issue now. Thank you!
